// Article Component - Unified Article Page Structure
class ArticleComponent {
    constructor(articleData) {
        this.data = articleData;
        this.relatedArticles = [];
    }

    async loadRelatedArticles() {
        // بارگذاری مقالات مرتبط (3 مقاله آخر به جز مقاله فعلی)
        try {
            const isSubPage = window.location.pathname.includes('/data/articles/');
            const basePath = isSubPage ? '../../' : '';
            
            const response = await fetch(`${basePath}data/articles/articles.json`);
            if (response.ok) {
                const articlesData = await response.json();
                this.relatedArticles = articlesData.articles
                    .filter(a => a.id !== this.data.id && a.active !== false)
                    .slice(0, 3);
            }
        } catch (err) {
            console.log('Could not load related articles');
        }
    }

    renderRelatedArticles() {
        if (!this.relatedArticles || this.relatedArticles.length === 0) return '';
        
        const isSubPage = window.location.pathname.includes('/data/articles/');
        
        const articlesHtml = this.relatedArticles.map((article, index) => {
            const articleFile = article.file || `article-${article.id}.html`;
            const articlePath = isSubPage ? articleFile : `data/articles/${articleFile}`;
            const imagePath = isSubPage ? '../../assets/images/' : 'assets/images/';
            
            // استخراج نام تصویر از فایل مقاله
            let coverImage = 'network.png'; // پیش‌فرض
            if (article.id === '1') coverImage = 'ai.png';
            else if (article.id === '2') coverImage = 'war.png';
            else if (article.id === '3') coverImage = 'sms.png';
            else if (article.id === '4') coverImage = 'ramzarz/cover.png';
            else if (article.id === '5') coverImage = 'network.png';
            
            return `
                <a href="${articlePath}" class="related-article-card">
                    <div class="related-article-number">${index + 1}</div>
                    <img src="${imagePath}${coverImage}" alt="${article.title}" class="related-article-image">
                    <div class="related-article-content">
                        <h4 class="related-article-title">${article.title}</h4>
                    </div>
                </a>
            `;
        }).join('');
        
        return `
            <div class="related-articles-section">
                <h3>یادداشت‌های پیشنهادی</h3>
                <div class="related-articles-grid">
                    ${articlesHtml}
                </div>
            </div>
        `;
    }

    renderTableOfContents() {
        return `
            <div class="toc-section">
                <h4>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <line x1="8" y1="6" x2="21" y2="6"></line>
                        <line x1="8" y1="12" x2="21" y2="12"></line>
                        <line x1="8" y1="18" x2="21" y2="18"></line>
                        <line x1="3" y1="6" x2="3.01" y2="6"></line>
                        <line x1="3" y1="12" x2="3.01" y2="12"></line>
                        <line x1="3" y1="18" x2="3.01" y2="18"></line>
                    </svg>
                    فهرست مطالب
                </h4>
                <ul class="toc-list" id="tocList">
                    <!-- Generated by JavaScript -->
                </ul>
            </div>
        `;
    }

    renderShareButtons() {
        return `
            <button class="share-btn linkedin" title="LinkedIn">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                </svg>
            </button>
            <button class="share-btn whatsapp" title="WhatsApp">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/>
                </svg>
            </button>
            <button class="share-btn telegram" title="Telegram">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/>
                </svg>
            </button>
            <button class="share-btn twitter" title="X (Twitter)">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                </svg>
            </button>
            <button class="share-btn copy" title="کپی لینک">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                </svg>
            </button>
        `;
    }

    renderSidebar() {
        return `
            <aside class="article-sidebar-left">
                ${this.renderTableOfContents()}
                
                <div class="sidebar-card">
                    <h4>اشتراک‌گذاری</h4>
                    <div class="share-buttons">
                        ${this.renderShareButtons()}
                    </div>
                </div>
            </aside>
        `;
    }

    renderMeta() {
        return `
            <div class="article-meta">
                <div class="article-meta-item">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                        <line x1="16" y1="2" x2="16" y2="6"></line>
                        <line x1="8" y1="2" x2="8" y2="6"></line>
                        <line x1="3" y1="10" x2="21" y2="10"></line>
                    </svg>
                    <span>${this.data.date}</span>
                </div>
                <div class="article-meta-divider"></div>
                <div class="article-meta-item">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                        <circle cx="12" cy="7" r="4"></circle>
                    </svg>
                    <span>${this.data.author}</span>
                </div>
                <div class="article-meta-divider"></div>
                <div class="article-meta-item">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <circle cx="12" cy="12" r="10"></circle>
                        <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    <span>${this.data.readingTime} دقیقه مطالعه</span>
                </div>
            </div>
        `;
    }

    renderTags() {
        if (!this.data.tags || this.data.tags.length === 0) return '';
        
        const tagsHtml = this.data.tags.map(tag => 
            `<a href="#" class="tag">${tag}</a>`
        ).join('');
        
        return `
            <div class="article-tags">
                <h3>برچسب‌ها</h3>
                <div class="tags-list">
                    ${tagsHtml}
                </div>
            </div>
        `;
    }

    

    render() {
        return `
            <article data-id="${this.data.id}" 
                     data-category="${this.data.category}" 
                     data-author="${this.data.author}" 
                     data-date="${this.data.date}" 
                     data-reading-time="${this.data.readingTime}" 
                     data-excerpt="${this.data.excerpt}" 
                     data-tags="${this.data.tags ? this.data.tags.join(',') : ''}" 
                     data-featured="${this.data.featured || false}">
                
                <div class="article-content-container">
                    ${this.renderSidebar()}
                    
                    <main class="article-main-content">
                        <div class="article-body-card">
                            <img class="article-cover-image" src="${this.data.image}" alt="${this.data.title}">
                            
                            <div class="article-header">
                                <span class="article-category-badge">${this.data.category}</span>
                                <h1 class="article-main-title">${this.data.title}</h1>
                            </div>
                            
                            <div class="article-body-content">
                                ${this.renderMeta()}
                                
                                <div class="article-share-section">
                                    <h4>اشتراک‌گذاری:</h4>
                                    <div class="article-share-buttons">
                                        ${this.renderShareButtons()}
                                    </div>
                                </div>
                                
                                ${this.data.lede ? `<p class="article-lede">${this.data.lede}</p>` : ''}
                                
                                <div id="article-content-body">
                                    ${this.data.content}
                                </div>
                                
                                ${this.renderTags()}
                                
                                ${this.renderRelatedArticles()}
                            </div>
                        </div>
                    </main>
                </div>
            </article>
        `;
    }

    async mount(selector) {
        await this.loadRelatedArticles();
        const element = document.querySelector(selector);
        if (element) {
            element.innerHTML = this.render();
            this.attachEvents();
            this.generateTableOfContents();
        }
    }

    attachEvents() {
        // Share button functionality
        const shareButtons = document.querySelectorAll('.share-btn');
        shareButtons.forEach(btn => {
            btn.addEventListener('click', (e) => this.handleShare(e));
        });

        // Smooth scroll for TOC links
        document.addEventListener('click', (e) => {
            if (e.target.classList.contains('toc-link')) {
                e.preventDefault();
                const targetId = e.target.getAttribute('href').substring(1);
                const targetElement = document.getElementById(targetId);
                if (targetElement) {
                    targetElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            }
        });
    }

    handleShare(e) {
        const button = e.currentTarget;
        const url = window.location.href;
        const title = this.data.title;

        if (button.classList.contains('linkedin')) {
            window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`, '_blank');
        } else if (button.classList.contains('whatsapp')) {
            window.open(`https://wa.me/?text=${encodeURIComponent(title + ' ' + url)}`, '_blank');
        } else if (button.classList.contains('telegram')) {
            window.open(`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`, '_blank');
        } else if (button.classList.contains('twitter')) {
            window.open(`https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`, '_blank');
        } else if (button.classList.contains('copy')) {
            navigator.clipboard.writeText(url).then(() => {
                const originalTitle = button.getAttribute('title');
                button.setAttribute('title', 'کپی شد!');
                setTimeout(() => button.setAttribute('title', originalTitle), 2000);
            });
        }
    }

    generateTableOfContents() {
        const content = document.getElementById('article-content-body');
        if (!content) return;

        const headings = content.querySelectorAll('h2, h3');
        const tocList = document.getElementById('tocList');
        if (!tocList || headings.length === 0) return;

        let tocHtml = '';
        headings.forEach((heading, index) => {
            const id = `heading-${index}`;
            heading.id = id;
            
            const number = index + 1;
            tocHtml += `
                <li class="toc-item">
                    <a href="#${id}" class="toc-link">
                        <span class="toc-number">${number}</span>
                        <span class="toc-text">${heading.textContent}</span>
                    </a>
                </li>
            `;
        });

        tocList.innerHTML = tocHtml;

        // Active TOC on scroll
        this.setupTOCScroll(headings);
    }

    setupTOCScroll(headings) {
        const tocLinks = document.querySelectorAll('.toc-link');
        
        window.addEventListener('scroll', () => {
            let current = '';
            
            headings.forEach(heading => {
                const sectionTop = heading.offsetTop;
                if (window.pageYOffset >= sectionTop - 100) {
                    current = heading.getAttribute('id');
                }
            });

            tocLinks.forEach(link => {
                link.classList.remove('active');
                if (link.getAttribute('href') === `#${current}`) {
                    link.classList.add('active');
                }
            });
        });
    }
}

// Export for use
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ArticleComponent;
}
